server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: false
        http-only: false
        name: SESSION
        domain: ~
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace