apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: dev-75b3b2d11686d9034647a400d1280847f1afc466

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml