apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: services-dev
nameSuffix: -dev

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: dev-bf34eb7347bc4579c67fc78abc0c9bdad5e54ee3

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml