apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-auth-api
    newName: jhjun07/jifelog-auth-api
    newTag: dev-9f471a79f6a34bba0f5ba25f200e9166644c7b5e

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml